### ISSUE TITLE
Scheduled HTTP Requests

### ISSUE THREAD

**Issue by modius** [alexdebrie/tutum-schedule#3]
@alexdebrie thanks for the scheduler.

In addition to tutum calls I'd like to be able to send simple HTTP requests to a REST API to kick off a periodic process.  Is there a simple way this can be done using the same framework?  It would be great to have our solutions periodic processes all wrapped up in the same place.

**Comment by alexdebrie** [comment]
Hey @modius, good question. When you run this, you have to make your own template of schedules and actions to run. An action is just a callback, so you can use whatever one you like. I've shown a few examples for Tutum, but you could use anything.

For example, you could write a simple ping function

``` python
@catch_exceptions
def ping(url):
    """
    Wrapper function to ping an endpoint
    """
    resp = requests.get(url)
    print resp
```

Then in your schedule, you would schedule the request with the time and url you want:

``` python
schedule.every().hour.do(ping, 'www.mysite.com/start_job/')
```

**Comment by modius** [comment]
thanks for that... have actually today just finished a http_request() job and added parallel threading ;)

Not sure how i put that back in a pull request.. maybe a bit too different.  Perhaps I'll create a separate repo and link back here. What would you prefer?

**Comment by alexdebrie** [comment]
Nice! Yea, it probably doesn't quite fit in this repo, but that'd be great to link back here.
